Use value-initialization to avoid -Wmaybe-uninitialized in gcc >=13
libMesh/MetaPhysicL pull request #47
Opened 2024-01-23 12:33 UTC by nmnobre

2024-01-23 16:18 UTC, roystgnr commented
Putting up a couple bits of the Slack conversation, for public record:

> Have you noticed a bunch of warnings, `warning: '<anonymous>' may be used uninitialized [-Wmaybe-uninitialized]` , when building MOOSE with gcc 13? The common thing to all these warnings seems to be that they happen when constructing `MetaPhysicL::DualNumber` objects.

> > Do you get any of them at the MetaPhysicL or libMesh build levels?  I did a bunch of --enable-paranoid-warnings --enable-werror gcc 13.2 builds late last year without seeing anything, but I don't think we have gcc 13 in CI and I don't ever turn on --enable-werror at the MOOSE level.

> I see them only when building MOOSE. I normally just use the default options as given by:
https://mooseframework.inl.gov/getting_started/installation/gcc_install_moose.html

> I’ve been playing with `ADVectorFunctionNeumannBC.C`, the initialisation in `ADVectorFunctionNeumannBC::computeQpResidual()` triggers the warning.
I’ve found two extra things: 1) no warning using `METHOD=dbg` on *any* file and 2) `do_derivatives` seems to be the same for both the constructor and assignment triggered by `ADVectorFunctionNeumannBC::computeQpResidual()` (from both a gdb inspection and just printing).
I’ve just confirmed the warning remains in the current snapshot of gcc 14

I'm in favor of merging this PR - the downside is that it may slow down AD code infinitesimally (there's a reason why C/C++ don't just mandate zeroing everything in the first place), the upside is that it may fix something in the absolute worst class of bugs: using uninitialized data can give you correct answers over and over again until suddenly it doesn't.

But I'd much prefer to *understand* why newer GCC is complaining here.  Pinging @lindsayad, partly because he wrote most of `DynamicStdArrayWrapper`, mostly because he's the only other person I think might have a shot at figuring this out.

2024-01-23 18:05 UTC, lindsayad requested changes
Unfortunately, I'm strongly against this change. When we first introduced AD into MOOSE using the `NumberArray` container, the first or second function in profiling was always the initial zeroing of the array. It's why we moved to default initialization for `NumberArray` and why we also do it here. That was also back in the day when people were only using container sizes that maxed out at 81 at the most (50 for the default). Now people are configuring with container sizes of 300 and even larger for things like 3D mortar. We have valgrind recipes to catch uses of uninitialized data, so I am not very concerned about the warnings being emitted

2024-01-23 18:09 UTC, lindsayad commented
You can look back at https://github.com/roystgnr/MetaPhysicL/pull/34 for some discussion on this topic

2024-01-23 18:11 UTC, roystgnr commented
> We have valgrind recipes to catch uses of uninitialized data, so I am not very concerned about the warnings being emitted

Heh, that was a bit of Slack discussion I hadn't yet gotten around to archiving here:

> > I'm currently trying to wrap my head about why this isn't screaming in valgrind.  We have a bunch of valgrind recipes gatekeeping next->devel merges in MOOSE, and you'd think they'd have screamed bloody murder if we ever actually tried to use uninitialized data.

My original hope was that we could paper over the issue now and then I could try to distill the warning down to an understandable minimal reproduction and figure out the problem in the next year or so, but that was when I was guessing this would be only a minor performance change.  If there's actually a significant pessimization on the one hand vs a warning of a possible serious bug on the other then I'll have to start digging into it sooner...

2024-01-23 18:31 UTC, lindsayad commented
> I'm currently trying to wrap my head about why this isn't screaming in valgrind

My thought on this is that it's because we aren't using uninitialized data 😄  There is a lengthy discussion about this warning with `-Og` [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78394). There are people argue for moving it out of `-Wall`:
 
> In my experience with several code bases, having this warning in -Wall (as opposed to -Wextra) does more harm than good, with people doing random bad code changes to try and get the compiler to shut up.

2024-01-23 18:57 UTC, nmnobre commented
> My thought on this is that it's because we aren't using uninitialized data 😄 There is a lengthy discussion about this warning with `-Og` [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78394). There are people argue for moving it out of `-Wall`.

That's actually a good point. Since the warning doesn't show up with `METHOD=dbg`, only `METHOD=opt`, and both use `-Wall` and `-Wextra`. I've tried changed the compilation line for `METHOD=opt` (-O2): the warning doesn't show with `-O0`, `-O1`, or `-O3`!!! You can also keep `-O2` and define `-DDEBUG`, the warning goes away all the same!

I thought I was crazy yesterday when I found that https://github.com/libMesh/MetaPhysicL/compare/master...farscape-project:MetaPhysicL:freakish_gcc13 also silences the warning somehow, I'm not that surprised anymore. 😨

2024-01-23 19:08 UTC, roystgnr commented
When I last dove into a problem like this (only triggering in optimized builds with newer clang), the explanation turned out to be wild: the compilers were vectorizing some instructions, and when vectorizing something with e.g. 11 entries the way you do it is you pad out to 12 entries and run the SIMD ops on groups of 4, and that last group of 4 would end up having a 0 in the padding and would be rife for divide-by-zero exceptions.

But at least in that case there was a legitimate conflict between the compiler (which knows we don't care about that 12th entry) and the CPU (which sees you dividing by zero and was told to scream when you divide by zero and so screams) and the compiler had a flag to work around the problem.  Here, though, the warning is coming from the compiler; is it possible the left hand doesn't know what the right hand is doing?  An optimizer doing some crazy SIMD combined with a warning analyzer that doesn't know some of the MD might be dropped?

> My thought on this is that it's because we aren't using uninitialized data 😄

And now that "only triggering in optimized builds with newer clang" bit has me worrying - what's the newest compiler we've run MOOSE through valgrind with?  We might have something that's legitimately using uninitialized data but only when compiled with the gcc versions new enough to trigger the warnings, and still passing with older compilers through valgrind, just like we were fine with other clang until they got more aggressive with their optimizer.

2024-01-23 19:12 UTC, lindsayad commented
The compiler for valgrind is `C++ compiler (/opt/mpich/bin/mpicxx): g++ (GCC) 12.2.1 20221121 (Red Hat 12.2.1-7)`

2024-01-23 19:14 UTC, lindsayad commented
So maybe @nmnobre can try running `./run_tests` with `--valgrind` and his new compiler and see what he sees

2024-01-23 19:14 UTC, lindsayad commented
Our valgrind recipe uses `METHOD=oprof` so that would be `-O2`

2024-01-24 19:49 UTC, nmnobre commented
I'm curious, what's the representative problem you mentioned [here](https://github.com/roystgnr/MetaPhysicL/pull/34#issuecomment-446796312)?
Would it be easy for me to benchmark something similar?
It's all inlined, one would think the compiler (if able to do proper dataflow/use-def analysis) would be able to see that initialising to zero is pointless and not do it. But by the same logic, it shouldn't complain about the uninitialised data in the first place.

2024-01-24 20:47 UTC, lindsayad commented
I don't recall unfortunately. I wish my past self had just spelled it out. I would pick a mortar test in the contact module with some large `min_ad_size` for benchmarking. Looks like the `pdass_problems` directory would be a good place to look

2024-01-24 23:10 UTC, nmnobre commented
> So maybe @nmnobre can try running `./run_tests` with `--valgrind` and his new compiler and see what he sees

Do you have the exact line?

I ran this:

```
#!/bin/sh -x

gcc --version | head -1
mpiexec --version | head -2
valgrind --version

METHOD=dbg make -j12 2>&1 | grep "declared here"
METHOD=oprof make -j12 2>&1 | grep "declared here"

./run_tests -j12 --oprof --valgrind --valgrind-max-fails 10000 | tail -100
```

which stops at 50 errors (I'm sure all unrelated):

```
+ gcc --version
+ head -1
gcc (GCC) 13.2.0
+ mpiexec --version
+ head -2
HYDRA build details:
    Version:                                 4.1.2
+ valgrind --version
valgrind-3.17.0
+ METHOD=dbg
+ make -j12
+ grep 'declared here'
+ METHOD=oprof
+ make -j12
+ grep 'declared here'
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/variables/MooseVariableFE.C:983:31: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/variables/MooseVariableFE.C:983:31: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/variables/MooseVariableFE.C:983:31: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/variables/MooseVariableFE.C:983:31: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/variables/MooseVariableFE.C:983:31: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/variables/MooseVariableFE.C:983:31: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/bcs/ADVectorFunctionNeumannBC.C:43:67: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/bcs/ADVectorFunctionNeumannBC.C:43:67: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/utils/ColumnMajorMatrix.C:23:60: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/utils/ColumnMajorMatrix.C:23:60: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/dgkernels/ADDGKernel.C:214:53: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/dgkernels/ADDGKernel.C:214:53: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/dgkernels/ADDGKernel.C:162:53: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/dgkernels/ADDGKernel.C:162:53: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/constraints/ADPeriodicSegmentalConstraint.C:43:46: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/constraints/ADPeriodicSegmentalConstraint.C:43:46: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/constraints/ADPeriodicSegmentalConstraint.C:43:46: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/constraints/ADPeriodicSegmentalConstraint.C:43:46: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/interfacekernels/ADInterfaceKernel.C:206:23: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/interfacekernels/ADInterfaceKernel.C:206:23: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/interfacekernels/ADInterfaceKernel.C:134:23: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/interfacekernels/ADInterfaceKernel.C:134:23: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/interfacekernels/ADInterfaceKernel.C:206:23: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/interfacekernels/ADInterfaceKernel.C:206:23: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/interfacekernels/ADInterfaceKernel.C:134:23: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/framework/src/interfacekernels/ADInterfaceKernel.C:134:23: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/test/src/constraints/ADTestPeriodicSole.C:67:38: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/test/src/constraints/ADTestPeriodicSole.C:67:38: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/test/src/constraints/ADTestPeriodicSole.C:67:38: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/test/src/constraints/ADTestPeriodicSole.C:67:38: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/test/src/constraints/ADTestPeriodicSole.C:67:38: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/test/src/constraints/ADTestPeriodicSole.C:67:38: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/test/src/constraints/ADTestPeriodicSole.C:108:38: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/test/src/constraints/ADTestPeriodicSole.C:108:38: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/test/src/constraints/ADTestPeriodicSole.C:108:38: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/test/src/constraints/ADTestPeriodicSole.C:108:38: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/test/src/constraints/ADTestPeriodicSole.C:108:38: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/test/src/constraints/ADTestPeriodicSole.C:108:38: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/dense_matrix.h:915:40: note: '<anonymous>' declared here
/archive/nnobre/FE/moose/scripts/../libmesh/installed/include/libmesh/d [...]

2024-01-24 23:36 UTC, lindsayad commented
It looks like the common denominator there is MPI. I don't think any of those tests shown involve AD

2024-01-25 00:21 UTC, nmnobre commented
> It looks like the common denominator there is MPI. I don't think any of those tests shown involve AD

Yeah, that's what I meant to say :), thus why I asked for the line you use.
In the meantime, I realised I also need to set `--max-fails` to let it run to completion.
If in the end, all failing tests are those requiring 2+ MPI processes, I guess we can assume we're good.

2024-01-25 13:17 UTC, nmnobre commented
> I don't recall unfortunately. I wish my past self had just spelled it out. I would pick a mortar test in the contact module with some large `min_ad_size` for benchmarking. Looks like the `pdass_problems` directory would be a good place to look

Best out of ten, ran with `for i in {1..10}; do (time ./contact-opt -i test/tests/pdass_problems/ironing.i) 2>&1 >/dev/null | grep real | awk '{print $2}'; done`:

|   | default-init | value-init |
| ------------- | ------------- | -----|
| --with-derivative-size=64 | 6.459s | 9.883s |
| --with-derivative-size=200 | 6.587s | 14.313s |

The test requires `min_ad_size=200` but it doesn't crash with the default of 64, so I ran it both ways.
As Alex rightfully said, this fully demonstrates that the changes suggested in this PR are no good. :)
The only thing I can suggest is to up `METHOD=opt` to `-O3` for better performance, no warnings, and a bit more distinction vs `oprof`.

I'll let you close this PR in your own time, hopefully it wasn't a total waste of time.

Cheers,
-Nuno

2024-01-26 17:16 UTC, lindsayad commented
Definitely not a waste. Having you think about it and having us think about it again is good. And it's great to have a re-affirmation that

- the default init is still working as desired: leading to timings that are independent of configuration size
- the original design of the default init wasn't a meaningless optimization
- we're still (likely) not getting uses of uninitialized data

Thank you for running these diagnostics!!

2024-01-26 17:16 UTC, closed without merging

2024-01-26 17:17 UTC, lindsayad commented
The `-O3` is a great suggestion and it's one we talk about every once in a while. I honestly can't remember why we haven't done it. @roystgnr ?

2024-01-28 23:08 UTC, roystgnr commented
5 bad reasons (that used to be better reasons):

5\. -O3 usually has longer compile times.  This doesn't really bother me now that compilers have gotten faster faster than our code has gotten longer.

4\. -O3 often increases binary sizes from excessive unrolling.  This doesn't really bother me; our binaries still take up a fraction of the RAM of the systems they work on.

3\. -O3 is more likely to turn Undefined Behavior into runtime bugs.  This bothers me a bit, having *just* fixed undefined behavior in `all_second_order` with `interior_parent` links, but really the fix here is "fix any UB", not "use UB and less optimization and cross our fingers".

2\. -O3 has had more compiler bugs in the past.  This was a big issue in the first gcc versions used by libMesh, but I don't think it's been a serious issue for 15 years.

1\. -O3 is even more illegible in a debugger than -O2, but the solution here is not to debug with either.

And one good one:

-O3 can make code slower than -O2, commonly by unrolling things too far and causing more cache misses.  We're typically memory limited, and we use a lot of operator-overloading-for-loops in templates (which I'm reading can trigger the issue more often) so this is a real worry. ... but we should probably resolve it by benchmarking, not by guessing.

Actually, if we *really* want some speed, we might try playing with profile-directed optimization.  That's supposed to routinely give people 10%+ speedups, and the cost of running a bunch of application cases before recompiling your code isn't too much of a cost in the MOOSE context where most of our users are using binaries now.

2024-01-29 12:58 UTC, nmnobre commented
Well, for what it's worth, some quick testing shows that `-O3` brings no extra performance for the test above. And, worse, while it gets rid of the warning for `ADVectorFunctionNeumannBC.C`, it doesn't for other occurrences, so just forget I said anything. :/

2024-01-31 23:33 UTC, lindsayad commented
Well my confidence in valgrind is somewhat shaken today. Well my confidence in even knowing what is right in wrong in C++ is also a little shaken. I was coming up with a bonus c++ interview question today, which was going to be "what's wrong with this program"?
```c++
#include <iostream>
#include <memory>

class B
{
public:
  int data = 5;
  ~B() { std::cout << "B is destructing" << std::endl; }
};

class A
{
public:
  A(const B & foo) : _foo(foo) {}

  void print_foo() { std::cout << _foo.data << std::endl; }

private:
  const B & _foo;
};

int
main()
{
  std::unique_ptr<A> a;
  {
    const B b;
    a = std::make_unique<A>(b);
  }
  a->print_foo();
}
```
Here is a series of my command prompts:
```
lindad@pop-os:~/programming/cpp(master)$ g++ -g dangling-reference.cpp
lindad@pop-os:~/programming/cpp(master)$ ./a.out
B is destructing
5
lindad@pop-os:~/programming/cpp(master)$ g++ -O3 -Wall -Wextra dangling-reference.cpp
In member function ‘void A::print_foo()’,
    inlined from ‘int main()’ at dangling-reference.cpp:30:15:
dangling-reference.cpp:16:40: warning: ‘b.B::data’ may be used uninitialized [-Wmaybe-uninitialized]
   16 |   void print_foo() { std::cout << _foo.data << std::endl; }
      |                                   ~~~~~^~~~
dangling-reference.cpp: In function ‘int main()’:
dangling-reference.cpp:27:13: note: ‘b’ declared here
   27 |     const B b;
      |             ^
lindad@pop-os:~/programming/cpp(master)$ g++ -O2 -Wall -Wextra dangling-reference.cpp
In member function ‘void A::print_foo()’,
    inlined from ‘int main()’ at dangling-reference.cpp:30:15:
dangling-reference.cpp:16:40: warning: ‘b.B::data’ may be used uninitialized [-Wmaybe-uninitialized]
   16 |   void print_foo() { std::cout << _foo.data << std::endl; }
      |                                   ~~~~~^~~~
dangling-reference.cpp: In function ‘int main()’:
dangling-reference.cpp:27:13: note: ‘b’ declared here
   27 |     const B b;
      |             ^
lindad@pop-os:~/programming/cpp(master)$ g++ -O0 -Wall -Wextra dangling-reference.cpp
lindad@pop-os:~/programming/cpp(master)$ g++ -O1 -Wall -Wextra dangling-reference.cpp
lindad@pop-os:~/programming/cpp(master)$ valgrind ./a.out
==8599== Memcheck, a memory error detector
==8599== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==8599== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==8599== Command: ./a.out
==8599== 
B is destructing
5
==8599== 
==8599== HEAP SUMMARY:
==8599==     in use at exit: 0 bytes in 0 blocks
==8599==   total heap usage: 3 allocs, 3 frees, 74,760 bytes allocated
==8599== 
==8599== All heap blocks were freed -- no leaks are possible
==8599== 
==8599== For lists of detected and suppressed errors, rerun with: -s
==8599== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
lindad@pop-os:~/programming/cpp(master)$ g++ -fsanitize=address dangling-reference.cpp
lindad@pop-os:~/programming/cpp(master)$
```
Only compiling with `-O3` and `-O2` yields a warning of what I thought the problem with the code should be. Although my confidence was initially rattled, bolstered by my destructor prints I do believe that `-O3` and `-O2` have the right of it while the less optimized compiles, valgrind, and address sanitizer all have the (silent) wrong of it.

2024-01-31 23:44 UTC, lindsayad commented
Ok, with a little more help (adding a function call) valgrind gets it right
```c++
#include <iostream>
#include <memory>
#include <array>

class B
{
public:
  int data = 5;
  ~B() { std::cout << "B is destructing" << std::endl; }
};

class A
{
public:
  A(const B & foo) : _foo(foo) {}

  void print_foo() { std::cout << _foo.data << std::endl; }

private:
  const B & _foo;
};

std::unique_ptr<A>
makeA()
{
  const B b;
  return std::make_unique<A>(b);
}

std::unique_ptr<A>
makeA2()
{
  return std::make_unique<A>(B{});
}

int
main()
{
  std::unique_ptr<A> a;
  a = makeA();
  a->print_foo();
  a = makeA2();
  a->print_foo();
}
```
Output
```
lindad@pop-os:~/programming/cpp(master)$ valgrind ./a.out
==10208== Memcheck, a memory error detector
==10208== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==10208== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==10208== Command: ./a.out
==10208== 
B is destructing
==10208== Conditional jump or move depends on uninitialised value(s)
==10208==    at 0x49B705E: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, long) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x49C54A9: std::ostream& std::ostream::_M_insert<long>(long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x109537: A::print_foo() (dangling-reference.cpp:17)
==10208==    by 0x1093B7: main (dangling-reference.cpp:41)
==10208== 
==10208== Use of uninitialised value of size 8
==10208==    at 0x49B6F3B: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x49B7088: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, long) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x49C54A9: std::ostream& std::ostream::_M_insert<long>(long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x109537: A::print_foo() (dangling-reference.cpp:17)
==10208==    by 0x1093B7: main (dangling-reference.cpp:41)
==10208== 
==10208== Conditional jump or move depends on uninitialised value(s)
==10208==    at 0x49B6F4D: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x49B7088: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, long) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x49C54A9: std::ostream& std::ostream::_M_insert<long>(long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x109537: A::print_foo() (dangling-reference.cpp:17)
==10208==    by 0x1093B7: main (dangling-reference.cpp:41)
==10208== 
==10208== Conditional jump or move depends on uninitialised value(s)
==10208==    at 0x49B70BE: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, long) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x49C54A9: std::ostream& std::ostream::_M_insert<long>(long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x109537: A::print_foo() (dangling-reference.cpp:17)
==10208==    by 0x1093B7: main (dangling-reference.cpp:41)
==10208== 
31
B is destructing
==10208== Conditional jump or move depends on uninitialised value(s)
==10208==    at 0x49B705E: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, long) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x49C54A9: std::ostream& std::ostream::_M_insert<long>(long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x109537: A::print_foo() (dangling-reference.cpp:17)
==10208==    by 0x1093F6: main (dangling-reference.cpp:43)
==10208== 
==10208== Conditional jump or move depends on uninitialised value(s)
==10208==    at 0x49B70BE: std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<long>(std::ostreambuf_iterator<char, std::char_traits<char> >, std::ios_base&, char, long) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x49C54A9: std::ostream& std::ostream::_M_insert<long>(long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31)
==10208==    by 0x109537: A::print_foo() (dangling-reference.cpp:17)
==10208==    by 0x1093F6: main (dangling-reference.cpp:43)
==10208== 
31
==10208== 
==10208== HEAP SUMMARY:
==10208==     in use at exit: 0 bytes in 0 blocks
==10208==   total heap usage: 4 allocs, 4 frees, 74,768 bytes allocated
==10208== 
==10208== All heap blocks were freed -- no leaks are possible
==10208== 
==10208== Use --track-origins=yes to see where uninitialised values come from
==10208== For lists of detected and suppressed errors, rerun with: -s
==10208== ERROR SUMMARY: 12 errors from 6 contexts (suppressed: 0 from 0)
```

2024-01-31 23:46 UTC, lindsayad commented
Note that with the most recent program, the compiler never warns about possibly uninitialized values, no matter the optimization level I pass

2024-02-01 01:11 UTC, roystgnr commented
That's some horrible compiler warning quality there.

I'm actually surprised valgrind could catch any of that, though.  The problem isn't technically an uninitialized value (which memcheck is good at catching), it's a dangling reference (which I didn't know memcheck could catch at all).

2024-02-01 14:48 UTC, nmnobre commented
Interesting!

> and address sanitizer all have the (silent) wrong of it.

Seems to work for me, no matter the optimisation level: https://godbolt.org/z/r7dvzKzj9

2024-02-01 20:33 UTC, lindsayad commented
Oh nice! Maybe that's an improvement in gcc 13